---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    force: ${GALAXY_FORCE:-false}
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: podman

platforms:
  - name: "packman-${MOLECULE_SCENARIO_NAME}-opensuse-15.2"
    image: "quay.io/gotmax23/opensuse-systemd:15.2"
    command: ""
    pre_build_image: true
    systemd: true
  - name: "packman-${MOLECULE_SCENARIO_NAME}-opensuse-15.3"
    image: "quay.io/gotmax23/opensuse-systemd:15.3"
    command: ""
    pre_build_image: true
    systemd: true
  - name: "packman-${MOLECULE_SCENARIO_NAME}-opensuse-tumbleweed"
    image: "quay.io/gotmax23/opensuse-systemd:tumbleweed"
    command: ""
    pre_build_image: true
    systemd: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  playbooks:
    converge: "../playbooks/${CONVERGE_PLAYBOOK:-converge.yml}"
    prepare: "../playbooks/${PREPARE_PLAYBOOK:-prepare.yml}"
    verify: "../playbooks/${VERIFY_PLAYBOOK:-verify.yml}"
