---
- name: Test ansible-role-generator
  hosts: localhost
  gather_facts: false

  vars:
    generator_default_docker_image: opensuse
    generator_default_docker_tag: 15.3

    generator_molecule_wflow_test:
      skip_test_step: true
      steps:
        - name: ansible --version
          run: ansible --version

        - name: ansible-galaxy collection list community.general
          run: ansible-galaxy collection list community.general

        - name: ansible-config dump --only-changed
          run: ansible-config dump --only-changed

        - name: "Molecule test: packman_state=present"
          env:
            packman_state: present
          run: molecule test -s single --destroy never

        - name: "Molecule test: packman_state=absent"
          env:
            packman_state: absent
          run: molecule -vvvv test -s single --destroy never

        - name: "Molecule verify: packman_state=absent"
          if: always()
          env:
            packman_state: absent
          run: molecule -v verify -s single

        - name: Molecule destroy
          if: always()
          run: molecule destroy -s single

  roles:
    - gotmax23.generator


# vim: set filetype=yaml.ansible:
