---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    force: ${GALAXY_FORCE:-true}
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: "packman-${image:-opensuse}-${tag:-15.3}${TOX_ENVNAME}"
    image: "quay.io/gotmax23/${image:-opensuse}-systemd:${tag:-15.3}"
    command: ""
    pre_build_image: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /sys/fs/cgroup/systemd
      - /var/lib/journal
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  playbooks:
    converge: "../playbooks/${CONVERGE_PLAYBOOK:-converge.yml}"
    prepare: "../playbooks/${PREPARE_PLAYBOOK:-prepare.yml}"
    verify: "../playbooks/${VERIFY_PLAYBOOK:-verify.yml}"
