---
- name: Setup Packman Repository
  become: true
  when: ansible_os_family == "Suse"
  block:
    - name: Ensure variables are set correctly
      ansible.builtin.import_tasks: assert.yml
      delegate_to: localhost
      vars:
        ansible_connection: local
      become: false

    - name: "{{ installw }} Packamn GPG key"
      ansible.builtin.rpm_key:
        key: "{{ packman_gpg_key_url }}"
        fingerprint: "{{ packman_gpg_key_fingerprint if packman_check_key_fingerprint | bool else omit }}"
        state: "{{ packman_state }}"

    - name: "Install Packman Repository"
      when: packman_state == "present"
      notify: zypper_dist_upgrade
      community.general.zypper_repository:
        # state: "{{ packman_state }}"
        name: packman
        refresh: true
        priority: 90
        repo: "{{ packman_repo_url }}"

    - name: Remove Packamn Repository
      when: packman_state == "absent"
      ansible.builtin.file:
        path: /etc/zypp/repos.d/packman.repo
        state: absent
