---
- name: zypper_dist_upgrade
  become: true
  #  when: packman_state == "present"
  community.general.zypper:
    name: "*"
    state: dist-upgrade
    allow_vendor_change: true
    extra_args: "--from packman"
