---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    force: "${GALAXY_FORCE:-true}"
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: podman
platforms:
  - name: "packman-${image:-opensuse}-${tag:-15.3}${TOX_ENVNAME}"
    image: "quay.io/gotmax23/${image:-opensuse}-systemd:${tag:-15.3}"
    command: ""
    pre_build_image: true
    systemd: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: ansible
