---
#
# Ansible managed
#
name: Lint code and run Molecule tests

'on':
  push:
    paths-ignore:
      - README.md
      - .github/settings.yml
  pull_request:
    paths-ignore:
      - README.md
      - .github/settings.yml
  workflow_dispatch:
  schedule:
    - cron: "23 21 3 * *"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2

      - name: "Set up Python 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Generate cache keys
        id: keys
        run: |
          echo ::set-output name=pip_cache_dir::$(pip cache dir)
          echo ::set-output name=date::$(date +%Y_%g)

      - name: Pip Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.keys.outputs.pip_cache_dir }}
          key: ansible-pip-${{ steps.keys.outputs.date }}

      - name: Install pip packages
        run: |
          pip3 install -U pip
          pip3 install wheel
          pip3 install molecule molecule-podman ansible-core yamllint ansible-lint

      - name: Run molecule lint
        run: molecule lint -s single
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"

  test:
    runs-on: ubuntu-20.04
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        os:
          - image: "opensuse"
            tag: "15.2"
          - image: "opensuse"
            tag: "15.3"
          - image: "opensuse"
            tag: "tumbleweed"
    env:
      PY_COLORS: "1"
      ANSIBLE_FORCE_COLOR: "1"
      image: "${{ matrix.os.image }}"
      tag: "${{ matrix.os.tag }}"

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2

      - name: "Set up Python 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Generate cache keys
        id: keys
        run: |
          echo ::set-output name=pip_cache_dir::$(pip cache dir)
          echo ::set-output name=date::$(date +%Y_%g)

      - name: Pip Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.keys.outputs.pip_cache_dir }}
          key: ansible-pip-${{ steps.keys.outputs.date }}

      - name: Install pip packages
        run: |
          pip3 install -U pip
          pip3 install wheel
          pip3 install molecule molecule-podman ansible-core yamllint ansible-lint

      - name: Install containers.podman and community.general collections (Molecule dependency)
        run: |
          ansible-galaxy collection install containers.podman
          ansible-galaxy collection install community.general

      # This is necessary to allow running systemd in rootless containers.
      - name: Start systemd user service
        run: |
          loginctl enable-linger runner
          sleep 1
      - name: ansible --version
        run: ansible --version
      - name: ansible-galaxy collection list community.general
        run: ansible-galaxy collection list community.general
      - name: ansible-config dump --only-changed
        run: ansible-config dump --only-changed
      - env:
          packman_state: present
        name: 'Molecule test: packman_state=present'
        run: molecule test -s single --destroy never
      - env:
          packman_state: absent
        name: 'Molecule test: packman_state=absent'
        run: molecule -v test -s single --destroy never
      - env:
          packman_state: absent
        if: always()
        name: 'Molecule verify: packman_state=absent'
        run: molecule -v verify -s single
      - if: always()
        name: Molecule destroy
        run: molecule destroy -s single

